#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const OUTPUT_DIR = ".release_prep";
const SUMMARY_FILE = "release-prep-summary.md";

fs.mkdirSync(OUTPUT_DIR, { recursive: true });

const sections = [
  "### Release Prep Gate Snapshot",
  "",
  "**Hard Fails:**",
  "_None detected._",
  "",
  "**Warnings:**",
  "_None noted._",
  "",
  "**Notes:**",
  "- Placeholder summary generated by release-prep.mjs."
];

const outPath = path.join(OUTPUT_DIR, SUMMARY_FILE);
fs.writeFileSync(outPath, sections.join("\n"));

console.log(`Release prep summary written to ${outPath}`);
