name: "💬 Beta Feedback"
description: Share feedback on UX, performance, or features
labels: ["beta","feedback"]
body:
  - type: textarea
    id: summary
    attributes: { label: "Summary", placeholder: "What felt great? What was rough?" }
    validations: { required: true }
  - type: dropdown
    id: area
    attributes:
      label: "Area"
      options: ["Dashboard", "Extension", "Performance", "Onboarding", "Other"]
  - type: textarea
    id: details
    attributes: { label: "Details", placeholder: "Any context that helps" }
