name: CD • Extension

on:
  workflow_dispatch:
    inputs:
      channel:
        description: "beta | production"
        required: true
        default: "beta"

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CD extension workflow disabled in this branch"
