name: CD • Extension

on:
  workflow_dispatch:
    inputs:
      channel:
        description: "beta | production"
        required: true
        default: "beta"

permissions:
  contents: read
  actions: read
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CD extension workflow disabled in this branch"
