# NOTE:
# - Detector CI temporarily disabled pending full detector implementation.

name: 🔬 Detector CI (lint + coverage + bench)

on:
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Detector CI workflow disabled for current branch"
