name: Guard Lockfile & Package Manager

on:
  pull_request:
    branches: ['**']
    paths:
      - '**/package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/guard-lockfile.yml'
  workflow_dispatch: {}

jobs:
  guard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Verify canonical package manager
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            echo "::error ::pnpm-lock.yaml missing; reproducible builds require committing the lockfile."
            exit 1
          fi
          for bad in package-lock.json yarn.lock bun.lockb; do
            if git ls-files --error-unmatch "$bad" >/dev/null 2>&1; then
              echo "::error ::Forbidden lockfile present: $bad (use PNPM only)"
              exit 1
            fi
          done
      - name: Prepare pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.0.0
        with:
          version: 9
          run_install: false
      - name: Enable corepack
        run: corepack enable
      - name: pnpm fetch
        run: pnpm fetch
      - name: pnpm install (offline, frozen)
        run: pnpm install --offline --frozen-lockfile
